### ISSUE TITLE
ombi-bot has auto-approved permissions

### ISSUE THREAD

**Issue by daurpam** [StackTraceYo/plex-bot#41]
Thanks for your work!

This is a feature request more than an issue. 
Your bot works flawlessly, but the problem for me, its that all requests are auto-approved, and the vote limit that I've setup in ombi has no effect if users use ombi-bot in the telegram chat. 
Is there a way to set up bot to not auto-approve request and only register in ombi, to be voted lately?

Thanks, great work!

**Comment by chessmango** [comment]
This depends on the user you've setup on Ombi - irrelevant of the bot itself. In my case I created a specific user called ombibot for this, with 'standard' permissions on Ombi itself

**Comment by daurpam** [comment]
Thanks for the answer, and sorry, but I don't understand how to do that.
If I was using the API key of Ombi, how could assign this API key to a user with restrictions?
Regards

**Comment by chessmango** [comment]
Ah, just checked my config and yeah, global API key - but then OMBI_USER_NAME dictates which user the requests are made as. Could perhaps be better documented - I'll put together a PR :smile:

**Comment by chessmango** [comment]
Clarified in https://github.com/StackTraceYo/ombi-bot/pull/42 and https://github.com/StackTraceYo/ombi-bot/pull/43

**Comment by daurpam** [comment]
I created one user with only these roles: "admin, Request TV and Request Movie" and assign it to the bot. Now it doesn't search anything. 
In the other hand, the first time I've created the bot, can interact with it in the channel group, now it doesn't work. Don't understand why.

**Comment by daurpam** [comment]
Seems that something broken, perhaps with the last ombi updates.
*docker-compose.yml*
```
version: '3'

services:
  ombi-bot:
    image: stacktraceyo/ombi-bot
    container_name: ombi-bot
    environment:
      - OMBI_HOST=SOME_STUFF
      - OMBI_KEY=SOME_STUFF
      - OMBI_BOT_TOKEN=SOME_STUFF
      - OMBI_BOT_NAME=SOME_STUFF
      - OMBI_USER_NAME=SOME_STUFF
      - BOT_CHAT_ID=SOME_STUFF
      - BOT_ADMIN=SOME_STUFF
      - TZ=Europe/Madrid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
```
If I comment the environment fields "OMBI_USER_NAME, BOT_CHAT_ID & BOT_ADMIN" the requests and search works without problem, but there were auto-approve.
I've created a user in ombi with the next roles:
![image](https://user-images.githubusercontent.com/18077653/106058205-3b1be200-60f1-11eb-96b4-33a0d045831a.png)

And add the bot in channel as a administrator of the channel. 
With this config I have no results in the chat, even register the chat and authorize myself, never show results. 

But if no of the above fields were set it works.

**Comment by chessmango** [comment]
Hmm, odd. For reference, here's the relevant part of my compose file as configured, running Ombi v4 and ombi-bot's v4 branch. I'm specifically avoiding admin/auth for the bot itself, as I'm targeting a group. Same process applies to Ombi v3 - I switched because of a Plex library query fix.

```
  ombibot:
    image: "stacktraceyo/ombi-bot:2.2-OMBI-V4"
    networks:
      - "<my-network>"
    restart: "unless-stopped"
    environment:
      - "OMBI_HOST=http://ombi:3579"
      - "OMBI_KEY=<global-api-key>"
      - "OMBI_BOT_TOKEN=<my-bot-token>"
      - "OMBI_BOT_NAME=<my-bot-name>"
      - "OMBI_USER_NAME=ombibot"
      - "BOT_CHAT_ID=<my-chat-id>"
    depends_on:
      - "ombi"
```

For what it's worth as well, my `ombibot` user has permissions as follows (layout is v4, but same options)
![Perms](https://user-images.githubusercontent.com/8074719/106124616-f1b8aa80-6163-11eb-8c5f-7acd9c29f380.png)

So by setting `OMBI_USER_NAME`, that user's permissions apply to the request. Just out of curiosity, why are you exposing `/var/run/docker.sock` to the container? This shouldn't be necessary here, and is possibly not the most secure way to go about things.
